on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install mkdocs
      # まず、ビルドします。
      - run: mkdocs new docs
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          # デプロイ元リポジトリーとデプロイ先が異なる場合、
          # external_repository を指定します。
          external_repository: github-user-name/github-repository-name
          # publish_branch を指定しない場合、
          # gh-pages ブランチにデプロイされます。
          publish_branch: master
          publish_dir: ./site
